#!/usr/bin/python3
# -*- coding: utf-8 -*-

import sys

def CeaserCipher(string, key):
    result = ""
    for i in range(len(string)):
        char = string[i]
        if(char.isupper()):
            result += chr((ord(char) + key - 65) % 26 + 65)
        else:
            result += chr((ord(char) + key - 97) % 26 + 97)

    return result

    
 
string = sys.argv[1]
key = int(sys.argv[2])

print(CeaserCipher(string,key))
